# -*- coding: utf-8 -*-
"""3.2. Dictionary_ImageHistogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LgYj_aQY87NX4gb1kfQq5Bjsa1R2DwF

Hiển thị ảnh trên Colab
"""

import cv2
from google.colab.patches import cv2_imshow

cat_image = cv2.imread("/content/binary_cat.png",0)
cv2_imshow(cat_image)

"""tính toán số lần xuất hiện của mỗi giá trị pixel trong hình ảnh cat_image.

counts = dict() tạo một dictionary để lưu trữ số lần xuất hiện của mỗi giá trị pixel.

height, width = cat_image.shape lấy kích thước của hình ảnh.

Vòng lặp for lồng nhau duyệt qua từng pixel trong hình ảnh:

Vòng lặp for row in range(height) duyệt qua từng hàng của hình ảnh.

Vòng lặp for col in range(width) duyệt qua từng cột của hình ảnh.

Trong mỗi vòng lặp, cat_image[row, col] lấy giá trị của pixel tại vị trí (row, col).

counts.get(cat_image[row, col], 0) trả về số lần xuất hiện của giá trị pixel
trong dictionary counts, nếu không tồn tại thì trả về 0.

counts[cat_image[row, col]] = counts.get(cat_image[row, col], 0) + 1 tăng giá trị của số lần xuất hiện của giá trị pixel lên 1.

Cuối cùng, in ra dictionary counts chứa số lần xuất hiện của mỗi giá trị pixel.
"""

counts = dict()
height, width = cat_image.shape
for row in range(height):
  for col in range(width):
      counts[cat_image[row,col]] = counts.get(cat_image[row,col],0) + 1

print('Counts', counts)

"""sử dụng thư viện matplotlib để tạo biểu đồ cột, hiển thị số lần xuất hiện của mỗi giá trị pixel trong hình ảnh cat_image.

names = list(counts.keys()) và values = list(counts.values()) tạo ra danh sách tên (giá trị pixel) và danh sách giá trị (số lần xuất hiện tương ứng).

plt.bar(range(len(counts)), values, tick_label=names) tạo ra biểu đồ cột, với trục x là các chỉ số từ 0 đến số lượng giá trị (số lượng giá trị pixel), trục y là số lần xuất hiện của từng giá trị, và nhãn trục x được đặt là tên của từng giá trị pixel.

plt.show() hiển thị biểu đồ.
"""

import matplotlib.pyplot as plt

names = list(counts.keys())
values = list(counts.values())

plt.bar(range(len(counts)), values, tick_label=names)
plt.show()